# Site settings
title: abapGit Bunkai
email: info@abapgit-bunkai.org
description:learn abapGit with abapGit Bunkai  > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abapgit.org" # the base hostname & protocol for your site

twitter_username: @ABAPCodeRetreat
github_username: abapGit

# Build settings
markdown: kramdown
